<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Muserorganisasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Muserorganisasi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'muserorganisasi/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'muserorganisasi/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'muserorganisasi/index.html';
            $config['first_url'] = base_url() . 'muserorganisasi/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Muserorganisasi_model->total_rows($q);
        $muserorganisasi = $this->Muserorganisasi_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'muserorganisasi_data' => $muserorganisasi,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('muserorganisasi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Muserorganisasi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'UserID' => $row->UserID,
		'OrganisasiID' => $row->OrganisasiID,
	    );
            $this->load->view('muserorganisasi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('muserorganisasi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('muserorganisasi/create_action'),
	    'UserID' => set_value('UserID'),
	    'OrganisasiID' => set_value('OrganisasiID'),
	);
        $this->load->view('muserorganisasi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Muserorganisasi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('muserorganisasi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Muserorganisasi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('muserorganisasi/update_action'),
		'UserID' => set_value('UserID', $row->UserID),
		'OrganisasiID' => set_value('OrganisasiID', $row->OrganisasiID),
	    );
            $this->load->view('muserorganisasi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('muserorganisasi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('UserID', TRUE));
        } else {
            $data = array(
	    );

            $this->Muserorganisasi_model->update($this->input->post('UserID', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('muserorganisasi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Muserorganisasi_model->get_by_id($id);

        if ($row) {
            $this->Muserorganisasi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('muserorganisasi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('muserorganisasi'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('UserID', 'UserID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Muserorganisasi.php */
/* Location: ./application/controllers/Muserorganisasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-21 15:39:13 */
/* http://harviacode.com */